---
- name: Update apt packages
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Save the current Ubuntu release version into a variable
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: "u+x,g+x"

- name: Test Docker with hello world example
  shell: "docker run hello-world"
  register: hello_world_output

- name: Show output of hello word example
  debug:
    msg: "Container Output: {{hello_world_output.stdout}}"

- name: Set periodic Docker prune
  cron:
    name: docker-prune
    job: 'docker system prune -af --filter "until=$((30*24))h"'
    minute: "0"
    hour: "1"

- name: Remove useless packages
  apt:
    autoclean: yes

- name: Remove useless dependencies
  apt:
    autoremove: yes
