site:
	ansible-playbook -i hosts.yml site.yml --ask-become-pass

renew-certificates:
	ansible-playbook -i hosts.yml renew-certificates.yml --ask-become-pass

authorize:
	ansible-playbook -i hosts.yml authorize.yml --ask-become-pass

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml